In [1]:
import tensorflow as tf
from tensorflow import keras

In [2]:
a = tf.random.normal(shape=(2, 2))
b = tf.random.normal(shape=(2, 2))

with tf.GradientTape() as tape:
    tape.watch(a) 
    c = tf.sqrt(tf.square(a) + tf.square(b))  # Do some math using `a`
    dc_da = tape.gradient(c, a)
    print(dc_da)

tf.Tensor(
[[-0.5955604  0.5046168]
 [ 0.5017506  0.9406151]], shape=(2, 2), dtype=float32)


In [3]:
a / tf.sqrt(tf.square(a) + tf.square(b))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.5955604 ,  0.5046168 ],
       [ 0.5017506 ,  0.94061506]], dtype=float32)>

In [4]:
x = tf.random.normal(shape=(2, 2))

with tf.GradientTape() as tape:
    tape.watch(x)
    y = tf.sin(x) 
    
grads = tape.gradient(y, x)
print(grads)

tf.Tensor(
[[0.5635156  0.83611655]
 [0.3726832  0.6570135 ]], shape=(2, 2), dtype=float32)


In [5]:
a = tf.random.uniform(shape=[]) 
b = tf.random.uniform(shape=[])
c = tf.random.uniform(shape=[])
d = tf.random.uniform(shape=[])

loss_function = keras.losses.MeanSquaredError()

with tf.GradientTape() as tape:
    tape.watch(x)
    y = tf.sin(x) 
    y_pred = a + b*x + c*x**2 + d*x**3
    loss = loss_function(y_pred, y)
    grads = tape.gradient(y, x)
print(grads)

tf.Tensor(
[[0.5635156  0.83611655]
 [0.3726832  0.6570135 ]], shape=(2, 2), dtype=float32)


In [6]:
tf.cos(x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.5635156 , 0.83611655],
       [0.3726832 , 0.6570135 ]], dtype=float32)>