In [263]:
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np

### Finding gradients (derivatives) of differentiable functions using GradientTape

In [264]:
a = tf.random.normal(shape=(2, 2))
b = tf.random.normal(shape=(2, 2))

with tf.GradientTape() as tape:
    tape.watch(a) 
    c = tf.sqrt(tf.square(a) + tf.square(b))  
    
grads = tape.gradient(c, a)
print(grads)

tf.Tensor(
[[ 0.9696452   0.12884374]
 [-0.21364185  0.43097642]], shape=(2, 2), dtype=float32)


In [265]:
a / tf.sqrt(tf.square(a) + tf.square(b))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.9696452 ,  0.12884374],
       [-0.21364187,  0.43097642]], dtype=float32)>

In [266]:
x = tf.random.normal(shape=())

with tf.GradientTape() as tape:
    tape.watch(x)
    y = tf.sin(x) 
    
grads = tape.gradient(y, x)
print(grads)

tf.Tensor(0.5527726, shape=(), dtype=float32)


### Use GradientTape with loss function and backpropagation to update weights

In [267]:
a = tf.random.uniform(shape=(4,2)) 
b = tf.random.uniform(shape=(4,2))
c = tf.random.uniform(shape=(4,2))
d = tf.random.uniform(shape=(4,2))

a = tf.Variable(a)
b = tf.Variable(b)
c = tf.Variable(c)
d = tf.Variable(d)

In [268]:
x = tf.random.normal(shape=(4,2))

In [269]:
loss_function = keras.losses.MeanSquaredError()
optimizer = keras.optimizers.SGD(learning_rate=1e-3)

for i in range(10000):
    with tf.GradientTape() as tape:
        tape.watch(x)
        y = tf.sin(x) 
        y_pred = a + b*x + c*x**2 + d*x**3
        loss = loss_function(y_pred, y)
        grads = tape.gradient(loss, [a,b,c,d])
        optimizer.apply_gradients(zip(grads, [a,b,c,d]))

In [270]:
print(y_pred, y)

tf.Tensor(
[[-0.662019    0.01417505]
 [-0.23739554 -0.36533085]
 [ 0.6088554  -0.05569623]
 [-0.54483896  0.05589948]], shape=(4, 2), dtype=float32) tf.Tensor(
[[-0.66201854 -0.05191602]
 [-0.2774748  -0.42175078]
 [ 0.58992594 -0.12379215]
 [-0.5692844   0.03019659]], shape=(4, 2), dtype=float32)


In [271]:
x

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[-2.418084  , -0.05193937],
       [-0.28116468, -0.43537536],
       [ 0.63096714, -0.12411053],
       [-0.60563517,  0.03020118]], dtype=float32)>

In [274]:
tf.sin(x)

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[-0.66201854, -0.05191602],
       [-0.2774748 , -0.42175078],
       [ 0.58992594, -0.12379215],
       [-0.5692844 ,  0.03019659]], dtype=float32)>