In [9]:
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np

### Finding gradients (derivatives) of differentiable functions using GradientTape

In [10]:
a = tf.random.normal(shape=(2, 2))
b = tf.random.normal(shape=(2, 2))

with tf.GradientTape() as tape:
    tape.watch(a) 
    c = tf.sqrt(tf.square(a) + tf.square(b))  
    
grads = tape.gradient(c, a)
print(grads)

tf.Tensor(
[[-0.705473    0.9511604 ]
 [-0.32963067 -0.95702183]], shape=(2, 2), dtype=float32)


In [11]:
a / tf.sqrt(tf.square(a) + tf.square(b))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.705473  ,  0.9511604 ],
       [-0.32963067, -0.95702183]], dtype=float32)>

In [12]:
x = tf.random.normal(shape=())

with tf.GradientTape() as tape:
    tape.watch(x)
    y = tf.sin(x) 
    
grads = tape.gradient(y, x)
print(grads, tf.cos(x))

tf.Tensor(0.4512346, shape=(), dtype=float32) tf.Tensor(0.4512346, shape=(), dtype=float32)


### Use GradientTape with loss function and backpropagation to update weights

In [13]:
a = tf.random.uniform(shape=(4,2)) 
b = tf.random.uniform(shape=(4,2))
c = tf.random.uniform(shape=(4,2))
d = tf.random.uniform(shape=(4,2))

a = tf.Variable(a)
b = tf.Variable(b)
c = tf.Variable(c)
d = tf.Variable(d)

In [14]:
x = tf.random.normal(shape=(4,2))

In [15]:
loss_function = keras.losses.MeanSquaredError()
optimizer = keras.optimizers.SGD(learning_rate=1e-3)

for i in range(10000):
    with tf.GradientTape() as tape:
        tape.watch(x)
        y = tf.sin(x) 
        y_pred = a + b*x + c*x**2 + d*x**3
        loss = loss_function(y_pred, y)
        grads = tape.gradient(loss, [a,b,c,d])
        optimizer.apply_gradients(zip(grads, [a,b,c,d]))

In [16]:
print(y_pred, y)

tf.Tensor(
[[ 0.33441463 -0.9899305 ]
 [ 0.4665886   0.6242594 ]
 [ 0.9956882   0.77353823]
 [ 0.16524284  0.27180862]], shape=(4, 2), dtype=float32) tf.Tensor(
[[ 0.31865507 -0.9899323 ]
 [ 0.4341314   0.6105607 ]
 [ 0.99568594  0.7730677 ]
 [ 0.10354258  0.23933877]], shape=(4, 2), dtype=float32)


In [17]:
tf.sin(x)

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[ 0.31865507, -0.9899323 ],
       [ 0.4341314 ,  0.6105607 ],
       [ 0.99568594,  0.7730677 ],
       [ 0.10354258,  0.23933877]], dtype=float32)>