In [7]:
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np

In [8]:
a = tf.random.normal(shape=(2, 2))
b = tf.random.normal(shape=(2, 2))

with tf.GradientTape() as tape:
    tape.watch(a) 
    c = tf.sqrt(tf.square(a) + tf.square(b))  
    
grads = tape.gradient(c, a)
print(grads)

tf.Tensor(
[[-0.192953    0.54379064]
 [ 0.5125408  -0.99983335]], shape=(2, 2), dtype=float32)


In [9]:
a / tf.sqrt(tf.square(a) + tf.square(b))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.192953  ,  0.54379064],
       [ 0.5125408 , -0.99983335]], dtype=float32)>

In [10]:
a = tf.random.uniform(shape=(4,2)) 
b = tf.random.uniform(shape=(4,2))
c = tf.random.uniform(shape=(4,2))
d = tf.random.uniform(shape=(4,2))

a = tf.Variable(a)
b = tf.Variable(b)
c = tf.Variable(c)
d = tf.Variable(d)

In [11]:
x = tf.random.normal(shape=(4,2))

In [12]:
loss_function = keras.losses.MeanSquaredError()
optimizer = keras.optimizers.SGD(learning_rate=1e-3)

for i in range(10000):
    with tf.GradientTape() as tape:
        tape.watch(x)
        y = tf.sqrt(tf.square(a) + tf.square(b))  
        y_pred = a + b*x + c*x**2 + d*x**3
        loss = loss_function(y_pred, y)
        grads = tape.gradient(loss, [a,b,c,d])
        optimizer.apply_gradients(zip(grads, [a,b,c,d]))

In [13]:
print(y_pred, y)

tf.Tensor(
[[0.23563315 0.6726276 ]
 [0.22565769 0.62811774]
 [0.15558577 1.0032578 ]
 [0.43630648 0.24959707]], shape=(4, 2), dtype=float32) tf.Tensor(
[[0.14208224 0.64477146]
 [0.24787998 0.6281503 ]
 [0.14645828 1.0032582 ]
 [0.43630934 0.30422202]], shape=(4, 2), dtype=float32)


In [14]:
tf.sqrt(tf.square(a) + tf.square(b))

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[0.14207996, 0.6447724 ],
       [0.24787918, 0.6281503 ],
       [0.14645895, 1.0032582 ],
       [0.43630934, 0.3042195 ]], dtype=float32)>

In [15]:
#Recreate the above using Keras linear layers
#Create a linear layer

In [ ]:
class Linear(keras.layers.Layer):
    """y = w.x + b"""
    def __init__():
    
    def build():
    
    def call():
        

In [ ]:
linear_layer = ...
y = linear_layer(...)