In [5]:
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np

In [6]:
a = tf.random.normal(shape=(2, 2))
b = tf.random.normal(shape=(2, 2))

with tf.GradientTape() as tape:
    tape.watch(a) 
    c = tf.sqrt(tf.square(a) + tf.square(b))  
    
grads = tape.gradient(c, a)
print(grads)

tf.Tensor(
[[ 0.6362499  0.9665568]
 [-0.2528889 -0.7710915]], shape=(2, 2), dtype=float32)


In [7]:
a / tf.sqrt(tf.square(a) + tf.square(b))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.63624996,  0.9665568 ],
       [-0.2528889 , -0.7710915 ]], dtype=float32)>

In [8]:
a = tf.random.uniform(shape=(4,2)) 
b = tf.random.uniform(shape=(4,2))
c = tf.random.uniform(shape=(4,2))
d = tf.random.uniform(shape=(4,2))

a = tf.Variable(a)
b = tf.Variable(b)
c = tf.Variable(c)
d = tf.Variable(d)

In [9]:
x = tf.random.normal(shape=(4,2))

In [10]:
loss_function = keras.losses.MeanSquaredError()
optimizer = keras.optimizers.SGD(learning_rate=1e-3)

for i in range(10000):
    with tf.GradientTape() as tape:
        tape.watch(x)
        y = tf.sqrt(tf.square(a) + tf.square(b))  
        y_pred = a + b*x + c*x**2 + d*x**3
        loss = loss_function(y_pred, y)
        grads = tape.gradient(loss, [a,b,c,d])
        optimizer.apply_gradients(zip(grads, [a,b,c,d]))

In [11]:
print(y_pred, y)

tf.Tensor(
[[0.8796777  0.19617438]
 [0.4353652  0.913118  ]
 [1.0327889  0.6928762 ]
 [0.6080385  0.6103182 ]], shape=(4, 2), dtype=float32) tf.Tensor(
[[0.8710088  0.20552616]
 [0.43537965 1.0360976 ]
 [0.98291296 0.735644  ]
 [0.604417   0.6677035 ]], shape=(4, 2), dtype=float32)


In [12]:
tf.sqrt(tf.square(a) + tf.square(b))

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[0.8710088 , 0.20552501],
       [0.43537965, 1.0360936 ],
       [0.9829135 , 0.7356433 ],
       [0.6044175 , 0.6677023 ]], dtype=float32)>

In [13]:
#Recreate the above using Keras linear layers
#Create a linear layer

In [25]:
class Linear(keras.layers.Layer):
    """y = w.x + b"""
    def __init__(self, units=32, input_dim=32):
        super().__init__()
        self.w = self.add_weight(
            shape=(input_dim, units), initializer='random_normal', trainable=True
        )
        self.b = self.add_weight(shape=(units,), initializer='zeros', trainable=True)
    def call():
        return tf.matmul(inputs, self.w) + self.b

In [29]:
linear_layer = Linear(units=4, input_dim=2)
y = linear_layer(tf.ones((2,2)))

ValueError: invalid method signature

In [27]:
x = tf.random.normal(shape=(60000,2))
y = tf.sqrt(tf.square(x) + tf.square(c))  
x

<tf.Tensor: shape=(60000, 2), dtype=float32, numpy=
array([[ 0.5953045 , -0.3209684 ],
       [-0.22948276, -0.63771915],
       [-0.42702585, -1.2800786 ],
       ...,
       [ 1.0231763 ,  2.2527454 ],
       [-1.3207788 ,  0.10131565],
       [ 0.80330056,  0.94779223]], dtype=float32)>

In [ ]:
# get dataset for distance function
# which variables are we taking the derivative of?

In [28]:
y

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[0.8710088 , 0.20552501],
       [0.43537965, 1.0360936 ],
       [0.9829135 , 0.7356433 ],
       [0.6044175 , 0.6677023 ]], dtype=float32)>